#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-UUID-Tiny
Version  : 1.04
Release  : 28
URL      : https://cpan.metacpan.org/authors/id/C/CA/CAUGUSTIN/UUID-Tiny-1.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/C/CA/CAUGUSTIN/UUID-Tiny-1.04.tar.gz
Summary  : Pure Perl UUID Support With Functional Interface
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-UUID-Tiny-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Digest::MD5)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
UUID-Tiny Version 1.04
This is a Pure Perl module for the creation of UUIDs:
- version 1 time based (with random multicast MAC address)
- version 3 MD5 based
- version 4 random number based
- version 5 SHA-1 based

%package dev
Summary: dev components for the perl-UUID-Tiny package.
Group: Development
Provides: perl-UUID-Tiny-devel = %{version}-%{release}
Requires: perl-UUID-Tiny = %{version}-%{release}

%description dev
dev components for the perl-UUID-Tiny package.


%package perl
Summary: perl components for the perl-UUID-Tiny package.
Group: Default
Requires: perl-UUID-Tiny = %{version}-%{release}

%description perl
perl components for the perl-UUID-Tiny package.


%prep
%setup -q -n UUID-Tiny-1.04
cd %{_builddir}/UUID-Tiny-1.04

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/UUID::Tiny.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
